version: '3.9'
services:
  blogor:
    build: .
    image: devecorsoft/blogor:0.0.2
    ports:
      - '8000:8000'
    volumes:
      - ~/mirrors/cn/devecor/blog:/root/blog
    environment:
      blog_host: '/root/blog'