name: build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - run: python manage.py test

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Read current version
        id: read_current_version
        run: echo "::set-output name=version::$(cat version.txt)"

      - name: Read tag from github
        id: read_tag_from_github
        run: echo "::set-output name=tag::$(git tag -l ${{ steps.read_current_version.outputs.version }})"

      - name: Verifiy version
        if: ${{ steps.read_tag_from_github.outputs.tag != '' }}
        run: |
          echo "please bump up version first!"
          exit 1

      - name: Build docker image
        run: docker build -t devecorsoft/blogor:${{ steps.read_current_version.outputs.version }} -t devecorsoft/blogor:latest .

      - name: Publish to github
        run: |
          docker login ghcr.io -u devecor -p ${{ secrets.GITHUB_TOKEN }}
          docker tag devecorsoft/blogor:latest ghcr.io/devecorsoft/blogor:latest
          docker tag devecorsoft/blogor:latest ghcr.io/devecorsoft/blogor:${{ steps.read_current_version.outputs.version }}
          docker push ghcr.io/devecorsoft/blogor:${{ steps.read_current_version.outputs.version }}
          docker push ghcr.io/devecorsoft/blogor:latest
          docker logout ghcr.io

      - name: Publish to aliyun
        run: |
          docker login registry.cn-zhangjiakou.aliyuncs.com -u ${{ secrets.ALIYUN_CR_USER_NAME }} -p ${{ secrets.ALIYUN_CR_USER_PASS }}
          docker tag devecorsoft/blogor:latest registry.cn-zhangjiakou.aliyuncs.com/devecorsoft/blogor:latest
          docker tag devecorsoft/blogor:latest registry.cn-zhangjiakou.aliyuncs.com/devecorsoft/blogor:${{ steps.read_current_version.outputs.version }}
          docker push registry.cn-zhangjiakou.aliyuncs.com/devecorsoft/blogor:${{ steps.read_current_version.outputs.version }}
          docker push registry.cn-zhangjiakou.aliyuncs.com/devecorsoft/blogor:latest
          docker logout registry.cn-zhangjiakou.aliyuncs.com

      - name: Git tagging
        run: |
          git tag $(cat version.txt)
          git push origin --tags

  release-to-staging:
    needs: publish
    runs-on: [self-hosted, remote]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: Install ssh-key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          ssh-keyscan -H "dev.devecor.cn" >> ~/.ssh/known_hosts

      - name: Service up
        run: |
          ssh root@dev.devecor.cn '
            docker stop blogor;
            docker rm blogor;
            docker rmi registry.cn-zhangjiakou.aliyuncs.com/devecorsoft/blogor:latest;
            docker run -d -e "blog_home=/root/blog" -p 8000:8000 -v "/root/mirrors/cn/devecor/blog:/root/blog" --name blogor registry.cn-zhangjiakou.aliyuncs.com/devecorsoft/blogor:latest;
          '

      - name: Delete ssh-key
        run: rm ~/.ssh/id_ed25519
